server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://rm-2zezarc99437hpp1alo.mysql.rds.aliyuncs.com:3306/base-boot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    hikari:
      username: baseboot
      password: Sq123456
  jpa:
    show-sql: true #默認false 开启sql展示
    database: mysql
    #create 启动时删数据库中的表，然后创建，退出时不删除数据表
    #create-drop 启动时删数据库中的表，然后创建，退出时删除数据表 如果表不存在报错
    #update 如果启动时表格式不一致则更新表，原有数据保留
    #validate 项目启动表结构进行校验 如果不一致则报错
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl #指定jpa的自动表生成策略，驼峰自动映射为下划线格式
